package com.example.loops;

public enum RecipeSortOption {
    BY_TITLE_ASCENDING,
    BY_PREP_TIME_ASCENDING,
    BY_CATEGORY_ASCENDING,

    BY_TITLE__DESCENDING,
    BY_PREP_TIME_DESCENDING,
    BY_CATEGORY_DESCENDING
}
